#include <iostream>
#include <string>
using namespace std;

#define COUNT 10

class Node {
  public:
    string data;
    Node* left, *right;

    Node(string data) {
      this->data = data;
      this->left = NULL;
      this->right = NULL;
    }
};

void print2DUtil(Node *root, int space);
void print2D(Node *root);
int maxDepth(Node* node);
Node *lava();
Node *stone();
Node *sand();
Node *swamp();
Node *clay();
Node *steam();
Node *metal();
Node *lava();
Node *stone();
Node *sand();
Node *swamp();
Node *clay();
Node *steam();
Node *metal();
Node *energy();
Node *boiler();
Node *electricity();
Node *alcohol();
Node *vodka();
Node *glass();
Node *bricks();
Node *storm();
Node *dust();
Node *ash();
Node *life();
Node *egg();
Node *seeds();
Node *golem();
Node *human();
Node *sex();
Node *weeds();
Node *bacteria();
Node *moss();
Node *mushroom();
Node *fern();
Node *grass();
Node *plankton();
Node *worm();
Node *sulfur();
Node *fish();
Node *shell();
Node *limestone();
Node *cement();
Node *concrete();
Node *house();
Node *skyscraper();
Node *butterfly();
Node *snake();
Node *beetle();
Node *scorpion();
Node *tools();
Node *weapon();
Node *poison();
Node *poisonedWeapon();
Node *hunter();
Node *warrior();
Node *dinosaur();
Node *dragon();
Node *hero();
Node *bird();
Node *blood();
Node *vampire();
Node *lizard();
Node *beast();
Node *werewolf();
Node *domesticAnimal();
Node *milk();
Node *fertilizer();
Node *tobacco();
Node *reed();
Node *paper();
Node *turtle();
Node *dolphin();
Node *whale();
Node *meat();
Node *feather();
Node *wool();
Node *book();
Node *cigarette();
Node *alcoholic();
Node *wizard();
Node *demigod();
Node *corpse();
Node *assassin();
Node *thunderBird();
Node *pheonix();
Node *hut();
Node *ceramics();
Node *fabric();
Node *clothes();
Node *tree();
Node *wood();
Node *wheel();
Node *cart();
Node *coal();
Node *oil();
Node *car();
Node *airplane();
Node *chariot();
Node *steamEngine();
Node *locomotive();
Node *boat();
Node *ship();
Node *frigate();
Node *steamShip();
Node *saltpetre();
Node *gunPowder();
Node *firearm();
Node *field();
Node *wheat();
Node *flour();
Node *dough();
Node *bread();
Node *beer();
Node *zombie();
Node *ghoul();
Node *treant();
Node *ghost();